name: Build Plugin
on:
  push:
    branches:
      - main
      - rel_*
      - test/*
    tags:
      - 'v**'
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TARGET_NAME: synth-template
  PLUGIN_NAME: SynthTemplate

defaults:
  run:
    shell: bash

jobs:
  build_plugin:
    name: Build - Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare for JUCE
        uses: surge-synthesizer/sst-githubactions/prepare-for-juce@main
        with:
          os: Windows

      - name: Build release version
        if: github.event_name != 'pull_request'
        run: |
          cmake -S . -B ./build -Ax64 -DCMAKE_BUILD_TYPE=Release -DCOPY_AFTER_BUILD=FALSE -DGITHUB_ACTIONS_BUILD=TRUE
          cmake --build ./build --config Release --target ${TARGET_NAME}_all --parallel 3

      - name: Configure pull request version
        if: github.event_name == 'pull_request'
        run: |
          cmake -S . -B ./build -Ax64 -DCMAKE_BUILD_TYPE=Debug -DCOPY_AFTER_BUILD=FALSE -DGITHUB_ACTIONS_BUILD=TRUE

      - name: Build pull request version
        if: github.event_name == 'pull_request'
        run: |
          cmake --build ./build --config Debug --target ${TARGET_NAME}_all --parallel 3

      - name: Make windows zip
        if: github.event_name != 'pull_request'
        run: |
          mkdir build/inst

          cp LICENSE.md build/${TARGET_NAME}_assets
          cp resources/ReadmeZip.txt build/${TARGET_NAME}_assets
          pushd build/${TARGET_NAME}_assets
          ls -al

          7z a -r ../inst/${TARGET_NAME}-windows-${GITHUB_DATE}-`git rev-parse --short HEAD`.zip *

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          path: build/inst
          name: dawplugin-windows

  publish-plugin-nightly:
    name: Publish Nightly
    if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'David303ttl' }}
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - name: Upload to Nightly
        uses: surge-synthesizer/sst-githubactions/upload-to-release@main
        with:
          tag: Nightly
          reuse_tag: true
          create_tag: false
          token: ${{ secrets.GITHUB_TOKEN }}
          release_blurb_file: resources/NightlyBlurb.md

  publish-plugin-release:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/v') && github.repository_owner == 'David303ttl'
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - name: Upload to Release
        uses: surge-synthesizer/sst-githubactions/upload-to-release@main
        with:
          tag: ${{ github.ref_name }}
          reuse_tag: false
          create_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
